[project]
name = "fia-doc"
version = "0.0.1"
authors = [
  {email = "wang@jolpi.ca"},
  {name = "Xuanyi Wang"}
]
description = "Parse FIA PDF documents to get race data"
readme = "README.md"

requires-python = ">=3.10,<3.13"  # 3.10 should work but older versions may also be fine
dependencies = [
  "camelot-py[base]>=1.0.0,<2.0.0",
  "matplotlib>=3.4.0,<4.0.0",
  "pandas>=2.0.0,<3.0.0",
  "pydantic>=2.0.0,<3.0.0",
  "pymupdf==1.25.1",  # Seems related to pymupdf/PyMuPDF#4206? Check `assert option in formats`
  "requests>=2.28.0,<3.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
ignore-vcs = true
include = [
  "fiadoc/**"
]
exclude = [
  "fiadoc/tests/**"
]

[tool.hatch.build.targets.sdist]
include = [
  "fiadoc/**"
]
exclude = [
  "fiadoc/tests/**"
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "fiadoc/tests"
]
