name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U uv pip 
          python -m uv pip install -U -r requirements.txt
          python -m uv pip install -U pytest pytest-cov ruff
      - name: lint with ruff
        run: |
          python -m ruff check ./
      - name: Test with pytest
        run: |
          pytest tests/